sudo: require
services:
  - docker
before_install:
  - docker pull node:8-onbuild
install:
  - docker build -t probot-hello .
script:
  - docker run --rm probot-hello npm run test
  - docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: V5HEKPij321TfMSLYq3hd5hMyOPKj0o900tPkiT+j75mgHxu/Ht74lZWrd9ZlKH3sTT0x/SXFUuozirCcDkF2nq3+27NBQhpf1yp3eEyhbKbyEkNNLHz67f0SwDKRJ1N5N0iFWK6iamdQ82BdqIkghPeul62Qqs6BtkAXC9fHne42xK6BkXYZYiNoM5rdeLZGnHaxuCLQaR6pHAyW0hdRnfPa1yxmvTMW56q/ej/f/hFpbCFxyvdJdsBunDafbH/vVS9YXAPZ2I8PUSfWfAzTnChPg7feYHJzmAYd9CTeup2MCvoH5V3ZUpaw4gYgUtXGz5beJU34qkDcyi98YGSoIIabVyeagdC/238dv8bKKMTb+2Boqv3gKRxovEfh6BQ4eAK6ng8HYAVPQtx8bHjQ+owPWTQZGd2KkhxnOrEIN6rOZSo9RO+ctU0yZnb1eh8ppFBnAYGxB0stV+JIhcojI7K759NxCbjzvqfzJKg+gL9KgrbBxa7rwinkOR2KSJszS8V8nC2thMymsZejWABZoR+nk3MDDpFP497qbcobfF/FGB1BJ6+u/pwNnrQlgAE+pncS2nthNAKl7vLYivUOuVGCE8Akdy5Vnugul8y5wuK/piRBP71m5z0m24jYapdq5RE1Kivhcmvn1G3U/k76ICayGDdpRe3qslckYuCzUQ=
  on: heroku_production
  app: devops-probot-osk
